void PROY_loadProperties(tPanel * panel);
trAction* PROY_close (tComponent *,int );
trAction* KEYM_change (tComponent *,int );
trAction* KEYM_new (tComponent *,int );
trAction* KEYM_test (tComponent *,int );
trAction* KEYM_create (tComponent *,int );
void KEYM_load(tPanel * panel);
trAction* EDF_select (tComponent *,int );
trAction* EDF_new (tComponent *,int );
trAction* EDF_delete (tComponent *,int );
trAction* COLOR_change (tComponent *,int );
trAction* MSG_select (tComponent *,int );
trAction* COMP_callFrm (tComponent *,int );
trAction* COMP_callSelect (tComponent *,int );
trAction* COMP_setCallFrm (tComponent *,int );
trAction* VIEW_panelChange (tComponent *,int );
trAction* PROY_new (tComponent *,int );
trAction* PROY_open (tComponent *,int );
trAction* PROY_save (tComponent *,int );
void PROY_loadSave(tPanel * panel);
trAction* PROY_test (tComponent *,int );
void PROY_replace(tComponent * component);
trAction* PROY_properties (tComponent *,int );
trAction* MSG_buttons (tComponent *,int );
trAction* MSG_change (tComponent *,int );
void MSG_load(tPanel * panel);
trAction* COLOR_test (tComponent *,int );
trAction* COLOR_delete (tComponent *,int );
trAction* COLOR_new (tComponent *,int );
void COLOR_load(tPanel * panel);
trAction* VIEW_panelCalls (tComponent *,int );
void PANEL_load(tPanel * panel);
trAction* COMP_reqMoves (tComponent *,int );
void COMP_preEnterPanel(tComponent * component);
trAction* VIEW_showView (tComponent *,int,int );
void COMP_prePanelEnter(tPanel * panel);
void FUNC_load(tPanel * panel);
void MOVE_load(tPanel * panel);
void COMP_loadLABEL(tPanel * panel);
void COMP_loadBUTTON(tPanel * panel);
void SELECT_load(tTable * table);
trAction* SELECT_enter (tTable *,int );
void SELECT_list(tTable * table);
void SELECT_filePreShow(tEdit * edit);
int MyMain(int argc, char * argv[]);
int MyEnd();
extern SCREEN * scrSTD;
