extern SCREEN * scrSTD;
int MyMain(int argc, char * argv[]);
int MyEnd();
int OneTo9(int * caracter);
trAction* PROY_checkOpen (tComponent *,int );
trAction* PROY_exit (tComponent *,int );
trAction* PROY_close (tComponent *,int );
trAction* KEYM_change (tComponent *,int );
trAction* RUN_execute (tComponent *,int );
void KEYM_load(tPanel * panel);
trAction* KEYM_new (tComponent *,int );
trAction* TEST_keymap (tComponent *,int );
trAction* KEYM_delete (tComponent *,int );
trAction* KEYM_create (tComponent *,int );
void EDF_load(tPanel * panel);
trAction* EDF_select (tComponent *,int );
trAction* EDF_new (tComponent *,int );
trAction* EDF_delete (tComponent *,int );
trAction* COLOR_change (tComponent *,int );
trAction* MSG_select (tComponent *,int );
trAction* VIEW_panelChange (tComponent *,int );
trAction* VIEW_tableChange (tComponent *,int );
trAction* VIEW_editChange (tComponent *,int );
trAction* VIEW_copyChange (tComponent *,int );
trAction* PROY_new (tComponent *,int );
trAction* PROY_open (tComponent *,int );
void PROY_loadSave(tPanel * panel);
trAction* PROY_save (tComponent *,int );
trAction* PROY_test (tComponent *,int );
void PROY_loadProperties(tPanel * panel);
void PROY_replace(tComponent * component);
trAction* PROY_propertiesDoIt (tComponent *,int );
void MSG_load(tPanel * panel);
trAction* MSG_buttons (tComponent *,int );
trAction* TEST_msg (tComponent *,int );
trAction* MSG_change (tComponent *,int );
void COLOR_load(tPanel * panel);
trAction* TEST_color (tComponent *,int );
trAction* COLOR_delete (tComponent *,int );
trAction* COLOR_new (tComponent *,int );
void PANEL_load(tPanel * panel);
trAction* VIEW_panelComps (tComponent *,int );
trAction* VIEW_panelCalls (tComponent *,int );
trAction* VIEW_panelMove (tComponent *,int );
trAction* VIEW_panelDelete (tComponent *,int );
trAction* TEST_panel (tComponent *,int );
trAction* VIEW_panelDoIt (tComponent *,int );
void EDIT_load(tPanel * panel);
trAction* COMP_selectKEYM (tComponent *,int );
void COMP_deselectKEYM(tComponent * component);
trAction* VIEW_editDelete (tComponent *,int );
trAction* TEST_edit (tComponent *,int );
trAction* VIEW_editDoIt (tComponent *,int );
void TABLE_load(tPanel * panel);
trAction* COMP_addTableColumn (tComponent *,int );
trAction* COMP_delTableColumn (tComponent *,int );
trAction* COMP_selTableColumn (tComponent *,int );
trAction* VIEW_tableDelete (tComponent *,int );
trAction* TEST_table (tComponent *,int );
trAction* VIEW_tableDoIt (tComponent *,int );
void VIEW_copyLoad(tPanel * panel);
trAction* VIEW_copyDoIt (tComponent *,int );
void COMP_loadCopy(tPanel * panel);
void MOVE_load(tPanel * panel);
trAction* MOVE_selectHelp (tComponent *,int,int );
trAction* MOVE_enterPanel (tComponent *,int );
void COMP_preEnterPanel(tComponent * component);
trAction* MOVE_save (tComponent *,int );
void FUNC_load(tPanel * panel);
trAction* FUNC_save (tComponent *,int );
void MOVE_loadFunction(tPanel * panel);
trAction* MOVE_saveFunction (tComponent *,int );
void COMP_loadLABEL(tPanel * panel);
trAction* COMP_out (tComponent *,int );
trAction* COMP_reqCalls (tComponent *,int );
trAction* COMP_delete (tComponent *,int );
trAction* TEST_componentPanel (tComponent *,int );
trAction* COMP_labelDoIt (tComponent *,int );
void COMP_loadButton(tPanel * panel);
trAction* COMP_Visible (tComponent *,int );
trAction* COMP_reqMoves (tComponent *,int );
trAction* COMP_buttonDoIt (tComponent *,int );
void COMP_loadCkButton(tPanel * panel);
trAction* COMP_ckbuttonDoIt (tComponent *,int );
void COMP_loadLsButton(tPanel * panel);
trAction* COMP_lbData (tComponent *,int );
trAction* COMP_addList (tComponent *,int );
trAction* COMP_delList (tComponent *,int );
trAction* COMP_lsbuttonDoIt (tComponent *,int );
void COMP_loadField(tPanel * panel);
void COMP_deselectEdFunc(tComponent * component);
trAction* COMP_fieldDoIt (tComponent *,int );
void RUN_check(tPanel * panel);
void RUN_compile(tPanel * panel);
trAction* RUN_compileFile (tComponent *,int );
trAction* PROY_editMenu (tComponent *,int,int );
trAction* PROY_editOpen (tComponent *,int );
trAction* PROY_editSave (tComponent *,int );
trAction* PROY_editClose (tComponent *,int );
void SELECT_load(tTable * table);
trAction* SELECT_enter (tTable *,int );
trAction* SELECT_out (tTable *,int );
void SELECT_optionLoad(tTable * table);
void SELECT_optionUpdate(tTable * table);
trAction* SELECT_optionEnter (tTable *,int );
void SELECT_listViews(tTable * table);
void SELECT_listColors(tTable * table);
void SELECT_listCalls(tTable * table);
void SELECT_compLoad(tTable * table);
trAction* SELECT_compEnter (tTable *,int );
trAction* PROY_editPanel (tEdit *,int,int );
