void PANEL_set(tXmlPanelPtr cab, tXmlPanelPtr ult);
void PANEL_addComp(char * panel, tXmlComponentPtr comp);
void PANEL_delComp(tXmlPanelPtr panel,tXmlComponentPtr comp);
void TABLE_set(tXmlTablePtr cab, tXmlTablePtr ult);
void EDIT_set(tXmlEditPtr cab, tXmlEditPtr ult);
void PANEL_reset();
void TABLE_reset();
void EDIT_reset();
tXmlPanelPtr PANEL_get();
tXmlTablePtr TABLE_get();
tXmlEditPtr  EDIT_get();
trAction* VIEW_panelCalls (tComponent * component,int key);
trAction* VIEW_showView (tComponent * component,int key,int Fn);
tXmlFApplication * VIEW_getViewCalls();
void VIEW_updateViewMove(int tipo, tXmlMove * move);
tXmlMove * VIEW_getViewMove(int tipo);
tXmlCompPanelPtr VIEW_getPanelComps(char * panel);
void VIEW_reset();
tXmlPanelPtr VIEW_searchPanel(char * name);
tXmlTablePtr VIEW_searchTable(char * name);
tXmlEditPtr VIEW_searchEdit(char * name);
int VIEW_duplicate(int id, char * name);
int VIEW_useColor(char * color);
